# Generated by Django 4.1.7 on 2023-04-01 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attorney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialization', models.CharField(choices=[('Civil', 'Civil'), ('Commercial', 'Commercial'), ('Criminal', 'Criminal'), ('Family', 'Family'), ('Juvenile', 'Juvenile'), ('Tax', 'Tax')], max_length=50)),
                ('date_of_birth', models.DateField()),
                ('experience', models.CharField(choices=[('Junior', 'Junior'), ('Mid', 'Mid'), ('Senior', 'Senior')], max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('fee', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('type', models.CharField(choices=[('Physical Person', 'Physical Person'), ('Juridical Person', 'Juridical Person')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Lawsuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Civil', 'Civil'), ('Commercial', 'Commercial'), ('Criminal', 'Criminal'), ('Family', 'Family'), ('Juvenile', 'Juvenile'), ('Tax', 'Tax')], max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('courtDate', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lawsuits', to='api.client')),
            ],
        ),
        migrations.CreateModel(
            name='AttorneyOnLawsuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attRole', models.CharField(choices=[('Primary', 'Primary'), ('Secondary', 'Secondary')], max_length=50)),
                ('workType', models.CharField(choices=[('Documents', 'Documents'), ('Statement preparation', 'Statement preparation'), ('Evidence collection', 'Evidence collection')], max_length=50)),
                ('attorney', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.attorney')),
                ('lawsuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lawsuit')),
            ],
        ),
    ]
